### ISSUE TITLE
unsubscribe from room not working

### ISSUE THREAD

**Issue by Mykytyuk** [spideynr/surge-client#1]
when i use "channel.unsubscribe(room);"
catсh error!! - "Uncaught ReferenceError: room is not defined"

**Comment by nikosrossolatos** [comment]
Hello , @Mykytyuk you are perfectly right. I will need to update my example. Channel functionality has been a job in progress. You can use `surge.unsubscribe('room')` to unsubscribe from your room. 

I will be updating Channel to be able to run `channel.unsubscribe()` in a couple of days.

**Comment by Mykytyuk** [comment]
I will be grateful))

**Comment by nikosrossolatos** [comment]
@Mykytyuk download or update to version 1.1.0 . Channel should be working after c70ffcc .

I have updated both github and npm to include changes.

**Comment by Mykytyuk** [comment]
thanks, It works)
